apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: bulletinnet
  name: bulletinnet
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: bulletinnet
    spec:
      containers:
      - env:
        - name: GET_HOST_FROM
          value: dns
        image: kisulken/buklletinapi:v1
        name: bulletinapi
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /go/src/bulletinApi
          name: bulletinnet-claim0
      hostname: bulletinapi
      restartPolicy: Always
      volumes:
      - name: bulletinnet-claim0
        persistentVolumeClaim:
          claimName: bulletinnet-claim0
status: {}
